export const entries = [
    //单对象控件
    {
      "name": "Operation",
      "note": "按钮",
      "path": "form/Operation.vue",
      "module": "form/single",
      "icon": "&#xe62f",
    },
    {
      "name": "TextInput",
      "note": "文本框",
      "path": "form/TextInput.vue",
      "module": "form/single",
      "icon": "&#xe624",
    },
    {
      "name": "NumberInput",
      "note": "数字框",
      "path": "form/NumberInput.vue",
      "module": "form/single",
      "icon": "&#xe628",
    },
    {
      "name": "DateInput",
      "note": "日期框",
      "path": "form/DateInput.vue",
      "module": "form/single",
      "icon": "&#xe62b",
    },
    {
      "name": "Label",
      "note": "标签",
      "path": "form/Label.vue",
      "module": "form/single",
      "icon": "&#xe619",
    },
    {
      "name": "QRcode",
      "note": "二维码",
      "path": "form/QRcode.vue",
      "module": "form/multi",
      "icon": "&#xe6f3",
    },
    {
      "name": "DropDownMenu",
      "note": "下拉菜单",
      "path": "form/DropDownMenu.vue",
      "module": "form/multi",
      "icon": "&#xe6d5",
    },
    {
      "name": "Card",
      "note": "商品卡片",
      "path": "form/Card.vue",
      "module": "form/multi",
      "icon": "&#xe6d6",
    },
    {
      "name": "Swipe",
      "note": "轮播",
      "path": "form/Swipe.vue",
      "module": "form/multi",
      "icon": "&#xe6cf",
    },
    {
      "name": "Grid",
      "note": "宫格",
      "path": "form/Grid.vue",
      "module": "form/multi",
      "icon": "&#xe6d0",
    },
    {
      "name": "TimeSteps",
      "note": "时间轴",
      "path": "form/TimeSteps.vue",
      "module": "form/multi",
      "icon": "&#xe6d8",
    },
    {
      "name": "Steps",
      "note": "步骤条",
      "path": "form/Steps.vue",
      "module": "form/multi",
      "icon": "&#xe6da",
    },
    {
      "name": "Calendar",
      "note": "日历",
      "path": "form/Calendar.vue",
      "module": "form/multi",
      "icon": "&#xe62b",
    },
    {
      "name": "TreeSelect",
      "note": "树选择",
      "path": "form/TreeSelect.vue",
      "module": "form/multi",
      "icon": "&#xe6c8",
    },
    {
      "name": "col",
      "note": "单列",
      "path": "form/col.vue",
      "module": "form/layout",
      "icon": "&#xe6a7",
    },
    {
      "name": "row",
      "note": "多列",
      "path": "form/row.vue",
      "module": "form/layout",
      "icon": "&#xe6b9",
    },
    {
      "name": "Tab",
      "note": "标签页",
      "path": "form/Tab.vue",
      "module": "form/layout",
      "icon": "&#xe62a",
    },
    {
      "name": "RadioButton",
      "note": "单选框",
      "path": "form/RadioButton.vue",
      "module": "form/single",
      "icon": "&#xe621",
    },
    {
      "name": "CheckBox",
      "note": "复选框",
      "path": "form/CheckBox.vue",
      "module": "form/single",
      "icon": "&#xe61f",
    },
    {
      "name": "SelectInput",
      "note": "选择框",
      "path": "form/SelectInput.vue",
      "module": "form/single",
      "icon": "&#xe644",
    },
    {
      "name": "Switch",
      "note": "开关",
      "path": "form/Switch.vue",
      "module": "form/single",
      "icon": "&#xe623",
    },
    {
      "name": "Attachments",
      "note": "上传文件",
      "path": "form/Attachments.vue",
      "module": "form/single",
      "icon": "&#xe656",
    },
    {
      "name": "Cell",
      "note": "单元格",
      "path": "form/Cell.vue",
      "module": "form/single",
      "icon": "&#xe6d7",
    },
    {
      "name": "Stepper",
      "note": "步进器",
      "path": "form/Stepper.vue",
      "module": "form/single",
      "icon": "&#xe6f2",
    },
    {
      "name": "MapPoint",
      "note": "位置标记",
      "path": "form/MapPoint.vue",
      "module": "form/single",
      "icon": "&#xe649",
    },
    {
      "name": "Iframe",
      "note": "嵌入网页",
      "path": "form/Iframe.vue",
      "module": "form/single",
      "icon": "&#xe612",
    },
    {
      "name": "SearchCell",
      "note": "搜索框",
      "path": "form/SearchCell.vue",
      "module": "form/multi",
      "icon": "&#xe6d4",
    },
    {
      "name": "NoticeBar",
      "note": "通知栏",
      "path": "form/NoticeBar.vue",
      "module": "form/multi",
      "icon": "&#xe6d1",
    },
    {
      "name": "FormEngine",
      "note": "卡片",
      "path": "form/FormEngine.vue",
      "module": "form/multi",
      "icon": "&#xe612",
    },
    {
      "name": "DynamicDigitalLabel",
      "note": "动态数字",
      "path": "form/DynamicDigitalLabel.vue",
      "module": "form/visual",
      "icon": "&#xe68d",
    },
    {
      "name": "Table",
      "note": "表格",
      "path": "form/Table.vue",
      "module": "form/multi",
      "icon": "&#xe637",
    },
    //编码扩展
    {
      "name": "EChart",
      "note": "Echarts扩展",
      "path": "form/EChart.vue",
      "module": "form/code",
      "icon": "&#xe69e"
    },
    {
      "name": "SelfCode",
      "note": "Html扩展",
      "path": "form/SelfCode.vue",
      "module": "form/code",
      "icon": "&#xe69d",
    }
  ];